ALTER TABLE orders ADD COLUMN coupon_id UUID REFERENCES store_coupons(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN discount DOUBLE PRECISION NOT NULL DEFAULT 0.0;
ALTER TABLE orders ADD COLUMN coupon_code TEXT;

ALTER TABLE order_items ADD COLUMN addons JSONB NOT NULL DEFAULT '[]'::jsonb;
